#!/bin/bash
#
#  OpenPom $Revision: 16 $
#  $HeadURL: https://openpom.googlecode.com/svn/trunk/send-order $
# 
#  Copyright 2010, Exosec
#  Licensed under GPL Version 2.
#  http://www.gnu.org/licenses/
# 
#  $Date: 2010-09-13 10:24:33 +0200 (Mon, 13 Sep 2010) $
#
#
# This bash script is just an exemple,
# you must improve it for you needs
#
# called as: "$EXEC_CMD" "$CMD_FILE" "$cmd" &
# $cmd is multilined
#

# uncomment for debug
# out=/tmp/${0##*/}.$RANDOM
# echo $0 $* > $out
# exec 2>> $out
# set -x

[ $# -ne 2 ] && exit 2

echo "$2" > $1
exit $? 

